CHESS_MOD_DIR := $(USERMOD_DIR)

SRC_USERMOD += $(CHESS_MOD_DIR)/chess_module.c
SRC_USERMOD += $(CHESS_MOD_DIR)/chess_game.c
SRC_USERMOD += $(CHESS_MOD_DIR)/mcu-max.c
SRC_USERMOD += $(CHESS_MOD_DIR)/chal.c

CFLAGS_USERMOD += -I$(CHESS_MOD_DIR) -I$(CHESS_MOD_DIR)/../src -DMCUMAX_HASHING_ENABLED -DMCUMAX_HASH_TABLE_SIZE=4096
