/*
 * doom_cache.c — Pre-processed WAD lump cache for fast init on Thumby Color.
 *
 * Loads doom_cache.bin (generated by preprocess_wad.py) which contains
 * all lumps needed during DOOM init. Avoids hundreds of slow individual
 * WAD file reads through MicroPython stream I/O.
 */

#include "doom_cache.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

#ifdef __arm__
#include "py/runtime.h"
#include "py/stream.h"
#endif

/* Cache file format:
 * Header: "DCACHE01" (8) + num_entries (4) + data_offset (4)
 * Index:  [name(8) + offset(4) + size(4)] * num_entries
 * Data:   concatenated lump data
 */

typedef struct {
    char name[8];
    uint32_t offset;
    uint32_t size;
} cache_entry_t;

static cache_entry_t *cache_index = NULL;
static uint8_t *cache_data = NULL;
static int cache_count = 0;

/* Access the WAD lumpinfo to map lump numbers to names */
#include "w_wad.h"

int doom_cache_load(const char *path) {
    FILE *f = fopen(path, "rb");
    if (!f) return -1;

    /* Read header */
    char magic[8];
    uint32_t num_entries, data_offset;
    fread(magic, 1, 8, f);
    if (memcmp(magic, "DCACHE01", 8) != 0) { fclose(f); return -2; }
    fread(&num_entries, 4, 1, f);
    fread(&data_offset, 4, 1, f);

    /* Read index */
    cache_count = num_entries;
    cache_index = malloc(num_entries * sizeof(cache_entry_t));
    if (!cache_index) { fclose(f); return -3; }
    fread(cache_index, sizeof(cache_entry_t), num_entries, f);

    /* Read data blob */
    fseek(f, 0, SEEK_END);
    long file_size = ftell(f);
    long data_size = file_size - data_offset;
    fseek(f, data_offset, SEEK_SET);

    cache_data = malloc(data_size);
    if (!cache_data) { free(cache_index); cache_index = NULL; fclose(f); return -4; }
    fread(cache_data, 1, data_size, f);

    fclose(f);
    printf("DOOM cache: %d lumps, %ldKB data\n", cache_count, data_size/1024);
    return 0;
}

#ifdef __arm__
int doom_cache_load_mp(void *file_obj, size_t file_size) {
    mp_obj_t fobj = (mp_obj_t)file_obj;
    const mp_stream_p_t *stream_p = mp_get_stream(fobj);
    int errcode = 0;

    /* Seek to start */
    struct mp_stream_seek_t seek_s = { .offset = 0, .whence = 0 };
    stream_p->ioctl(fobj, MP_STREAM_SEEK, (mp_uint_t)(uintptr_t)&seek_s, &errcode);

    /* Read header */
    char magic[8];
    uint32_t num_entries, data_offset;
    stream_p->read(fobj, magic, 8, &errcode);
    if (memcmp(magic, "DCACHE01", 8) != 0) return -2;
    stream_p->read(fobj, &num_entries, 4, &errcode);
    stream_p->read(fobj, &data_offset, 4, &errcode);

    /* Read index */
    cache_count = num_entries;
    cache_index = malloc(num_entries * sizeof(cache_entry_t));
    if (!cache_index) return -3;
    stream_p->read(fobj, cache_index, num_entries * sizeof(cache_entry_t), &errcode);

    /* Read data blob */
    long data_size = file_size - data_offset;
    cache_data = malloc(data_size);
    if (!cache_data) { free(cache_index); cache_index = NULL; return -4; }

    /* Read in chunks to avoid timeout */
    size_t read_so_far = 0;
    while (read_so_far < (size_t)data_size) {
        size_t chunk = data_size - read_so_far;
        if (chunk > 4096) chunk = 4096;
        size_t got = stream_p->read(fobj, cache_data + read_so_far, chunk, &errcode);
        if (got == 0) break;
        read_so_far += got;
    }

    printf("DOOM cache: %d lumps, %ldKB data\n", cache_count, data_size/1024);
    return 0;
}
#endif

const void *doom_cache_find(const char *name, int *size) {
    if (!cache_index || !cache_data) return NULL;

    for (int i = 0; i < cache_count; i++) {
        if (strncasecmp(cache_index[i].name, name, 8) == 0) {
            if (size) *size = cache_index[i].size;
            return cache_data + cache_index[i].offset;
        }
    }
    return NULL;
}

const void *doom_cache_find_by_lumpinfo(int lumpnum, int *size) {
    if (!lumpinfo) return NULL;
    return doom_cache_find(lumpinfo[lumpnum].name, size);
}
