DOOM_MOD_DIR := $(USERMOD_DIR)
DOOM_DG_DIR := $(DOOM_MOD_DIR)/doomgeneric

# Our platform glue
SRC_USERMOD += $(DOOM_MOD_DIR)/doom_module.c
SRC_USERMOD += $(DOOM_MOD_DIR)/doom_core.c
SRC_USERMOD += $(DOOM_MOD_DIR)/doom_cache.c
SRC_USERMOD += $(DOOM_MOD_DIR)/w_file_xip.c

# doomgeneric core
SRC_USERMOD += $(DOOM_DG_DIR)/am_map.c
SRC_USERMOD += $(DOOM_DG_DIR)/d_event.c
SRC_USERMOD += $(DOOM_DG_DIR)/d_items.c
SRC_USERMOD += $(DOOM_DG_DIR)/d_iwad.c
SRC_USERMOD += $(DOOM_DG_DIR)/d_loop.c
SRC_USERMOD += $(DOOM_DG_DIR)/d_main.c
SRC_USERMOD += $(DOOM_DG_DIR)/d_mode.c
SRC_USERMOD += $(DOOM_DG_DIR)/d_net.c
SRC_USERMOD += $(DOOM_DG_DIR)/doomdef.c
SRC_USERMOD += $(DOOM_DG_DIR)/doomgeneric.c
SRC_USERMOD += $(DOOM_DG_DIR)/doomstat.c
SRC_USERMOD += $(DOOM_DG_DIR)/dstrings.c
SRC_USERMOD += $(DOOM_DG_DIR)/dummy.c
SRC_USERMOD += $(DOOM_DG_DIR)/f_finale.c
SRC_USERMOD += $(DOOM_DG_DIR)/f_wipe.c
SRC_USERMOD += $(DOOM_DG_DIR)/g_game.c
SRC_USERMOD += $(DOOM_DG_DIR)/gusconf.c
SRC_USERMOD += $(DOOM_DG_DIR)/hu_lib.c
SRC_USERMOD += $(DOOM_DG_DIR)/hu_stuff.c
SRC_USERMOD += $(DOOM_DG_DIR)/i_endoom.c
SRC_USERMOD += $(DOOM_DG_DIR)/i_input.c
SRC_USERMOD += $(DOOM_DG_DIR)/i_joystick.c
SRC_USERMOD += $(DOOM_DG_DIR)/i_scale.c
SRC_USERMOD += $(DOOM_DG_DIR)/i_sound.c
SRC_USERMOD += $(DOOM_DG_DIR)/i_system.c
SRC_USERMOD += $(DOOM_DG_DIR)/i_timer.c
SRC_USERMOD += $(DOOM_DG_DIR)/i_video.c
SRC_USERMOD += $(DOOM_DG_DIR)/icon.c
SRC_USERMOD += $(DOOM_DG_DIR)/info.c
SRC_USERMOD += $(DOOM_DG_DIR)/m_argv.c
SRC_USERMOD += $(DOOM_DG_DIR)/m_bbox.c
SRC_USERMOD += $(DOOM_DG_DIR)/m_cheat.c
SRC_USERMOD += $(DOOM_DG_DIR)/m_config.c
SRC_USERMOD += $(DOOM_DG_DIR)/m_controls.c
SRC_USERMOD += $(DOOM_DG_DIR)/m_fixed.c
SRC_USERMOD += $(DOOM_DG_DIR)/m_menu.c
SRC_USERMOD += $(DOOM_DG_DIR)/m_misc.c
SRC_USERMOD += $(DOOM_DG_DIR)/m_random.c
SRC_USERMOD += $(DOOM_DG_DIR)/memio.c
SRC_USERMOD += $(DOOM_DG_DIR)/mus2mid.c
SRC_USERMOD += $(DOOM_DG_DIR)/p_ceilng.c
SRC_USERMOD += $(DOOM_DG_DIR)/p_doors.c
SRC_USERMOD += $(DOOM_DG_DIR)/p_enemy.c
SRC_USERMOD += $(DOOM_DG_DIR)/p_floor.c
SRC_USERMOD += $(DOOM_DG_DIR)/p_inter.c
SRC_USERMOD += $(DOOM_DG_DIR)/p_lights.c
SRC_USERMOD += $(DOOM_DG_DIR)/p_map.c
SRC_USERMOD += $(DOOM_DG_DIR)/p_maputl.c
SRC_USERMOD += $(DOOM_DG_DIR)/p_mobj.c
SRC_USERMOD += $(DOOM_DG_DIR)/p_plats.c
SRC_USERMOD += $(DOOM_DG_DIR)/p_pspr.c
SRC_USERMOD += $(DOOM_DG_DIR)/p_saveg.c
SRC_USERMOD += $(DOOM_DG_DIR)/p_setup.c
SRC_USERMOD += $(DOOM_DG_DIR)/p_sight.c
SRC_USERMOD += $(DOOM_DG_DIR)/p_spec.c
SRC_USERMOD += $(DOOM_DG_DIR)/p_switch.c
SRC_USERMOD += $(DOOM_DG_DIR)/p_telept.c
SRC_USERMOD += $(DOOM_DG_DIR)/p_tick.c
SRC_USERMOD += $(DOOM_DG_DIR)/p_user.c
SRC_USERMOD += $(DOOM_DG_DIR)/r_bsp.c
SRC_USERMOD += $(DOOM_DG_DIR)/r_data.c
SRC_USERMOD += $(DOOM_DG_DIR)/r_draw.c
SRC_USERMOD += $(DOOM_DG_DIR)/r_main.c
SRC_USERMOD += $(DOOM_DG_DIR)/r_plane.c
SRC_USERMOD += $(DOOM_DG_DIR)/r_segs.c
SRC_USERMOD += $(DOOM_DG_DIR)/r_sky.c
SRC_USERMOD += $(DOOM_DG_DIR)/r_things.c
SRC_USERMOD += $(DOOM_DG_DIR)/s_sound.c
SRC_USERMOD += $(DOOM_DG_DIR)/sha1.c
SRC_USERMOD += $(DOOM_DG_DIR)/sounds.c
SRC_USERMOD += $(DOOM_DG_DIR)/st_lib.c
SRC_USERMOD += $(DOOM_DG_DIR)/st_stuff.c
SRC_USERMOD += $(DOOM_DG_DIR)/statdump.c
SRC_USERMOD += $(DOOM_DG_DIR)/tables.c
SRC_USERMOD += $(DOOM_DG_DIR)/v_video.c
SRC_USERMOD += $(DOOM_DG_DIR)/w_checksum.c
SRC_USERMOD += $(DOOM_DG_DIR)/w_file.c
SRC_USERMOD += $(DOOM_DG_DIR)/w_file_stdc.c
SRC_USERMOD += $(DOOM_DG_DIR)/w_main.c
SRC_USERMOD += $(DOOM_DG_DIR)/w_wad.c
SRC_USERMOD += $(DOOM_DG_DIR)/wi_stuff.c
SRC_USERMOD += $(DOOM_DG_DIR)/z_zone.c

CFLAGS_USERMOD += -I$(DOOM_MOD_DIR)
CFLAGS_USERMOD += -I$(DOOM_DG_DIR)
CFLAGS_USERMOD += -I$(DOOM_MOD_DIR)/../src/io
CFLAGS_USERMOD += -DDOOM_THUMBY=1
CFLAGS_USERMOD += -DDOOMGENERIC_RESX=128
CFLAGS_USERMOD += -DDOOMGENERIC_RESY=128
CFLAGS_USERMOD += -URANGECHECK

# Suppress warnings that doomgeneric triggers under -Werror
# These are safe: the original DOOM code is well-tested, just old C style
CFLAGS_USERMOD += -Wno-sign-compare
CFLAGS_USERMOD += -Wno-missing-field-initializers
CFLAGS_USERMOD += -Wno-unused-variable
CFLAGS_USERMOD += -Wno-unused-but-set-variable
CFLAGS_USERMOD += -Wno-sometimes-uninitialized
CFLAGS_USERMOD += -Wno-implicit-fallthrough
CFLAGS_USERMOD += -Wno-double-promotion
CFLAGS_USERMOD += -Wno-format-truncation
CFLAGS_USERMOD += -Wno-type-limits
CFLAGS_USERMOD += -Wno-enum-conversion
CFLAGS_USERMOD += -Wno-unused-parameter
CFLAGS_USERMOD += -Wno-unused-but-set-parameter
CFLAGS_USERMOD += -Wno-unused-result
CFLAGS_USERMOD += -Wno-missing-braces
CFLAGS_USERMOD += -Wno-pointer-sign
